### ISSUE TITLE
channel.members can run into concurrent map read/write similar to client lookup set could be

### ISSUE THREAD

**Issue by DanielOaks** [DanielOaks/oragono#78]
Essentially as in the title.

We should solve this similarly to client lookup set I think, using RWLocks. We should also migrate the ClientLookupSet one to use an RWLock as appropriate.

```
fatal error: concurrent map read and map write

goroutine 12 [running]:
runtime.throw(0x42f52b, 0x21)
        /Users/dan/code/go-root/src/runtime/panic.go:566 +0x95 fp=0xc420041ba8 sp=0xc420041b88
runtime.mapaccess2_fast64(0x3ec1c0, 0xc4201b2750, 0xc4200aa700, 0xffffffffffffffff, 0x0)
        /Users/dan/code/go-root/src/runtime/hashmap_fast.go:156 +0x1b1 fp=0xc420041bd0 sp=0xc420041ba8
github.com/DanielOaks/oragono/irc.(*Channel).Join(0xc420019c30, 0xc4200aa700, 0x0, 0x0)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/channel.go:204 +0x60 fp=0xc420041d08 sp=0xc420041bd0
github.com/DanielOaks/oragono/irc.joinHandler(0xc42009d380, 0xc4200aa700, 0xc4201c0000, 0x0, 0x0, 0xc4201bc010, 0x4, 0xc4201bc020, 0x1, 0x1, ...)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/server.go:741 +0x34c fp=0xc420041e28 sp=0xc420041d08
github.com/DanielOaks/oragono/irc.(*Command).Run(0xc420041f28, 0xc42009d380, 0xc4200aa700, 0xc4201c0000, 0x0, 0x0, 0xc4201bc010, 0x4, 0xc4201bc020, 0x1, ...)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/commands.go:45 +0xce fp=0xc420041eb8 sp=0xc420041e28
github.com/DanielOaks/oragono/irc.(*Client).run(0xc4200aa700)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:171 +0x406 fp=0xc420041fa8 sp=0xc420041eb8
runtime.goexit()
        /Users/dan/code/go-root/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420041fb0 sp=0xc420041fa8
created by github.com/DanielOaks/oragono/irc.NewClient
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:129 +0x436

goroutine 1 [select]:
github.com/DanielOaks/oragono/irc.(*Server).Run(0xc42009d380)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/server.go:364 +0x7f5
main.main()
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/oragono.go:95 +0xa75

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /Users/dan/code/go-root/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /Users/dan/code/go-root/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /Users/dan/code/go-root/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /Users/dan/code/go-root/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc420091ea0)
        /Users/dan/code/go/src/github.com/tidwall/buntdb/buntdb.go:542 +0xe4
created by github.com/tidwall/buntdb.Open
        /Users/dan/code/go/src/github.com/tidwall/buntdb/buntdb.go:165 +0x222

goroutine 7 [IO wait]:
net.runtime_pollWait(0xa59090, 0x72, 0x0)
        /Users/dan/code/go-root/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42015f560, 0x72, 0xc42003fd00, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42015f560, 0x5ce520, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc42015f500, 0x0, 0x5ccca0, 0xc4201ad2e0)
        /Users/dan/code/go-root/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc42002e9e0, 0xc42003fdd8, 0xc42003fdd8, 0x82c4)
        /Users/dan/code/go-root/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc42002e9e0, 0xc42003fec8, 0xc42016c900, 0x0, 0xc42008f3c8)
        /Users/dan/code/go-root/src/net/tcpsock.go:222 +0x49
github.com/DanielOaks/oragono/irc.(*Server).createListener.func1(0xc42016e8d0, 0xc420115400, 0xc42009d380, 0xc420161a90, 0xd, 0xc42002e9d8, 0xc4201630c0)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/server.go:456 +0x69
created by github.com/DanielOaks/oragono/irc.(*Server).createListener
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/server.go:509 +0x555

goroutine 8 [select, locked to thread]:
runtime.gopark(0x45d888, 0x0, 0x424856, 0x6, 0x18, 0x2)
        /Users/dan/code/go-root/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42002d730, 0x0, 0x18)
        /Users/dan/code/go-root/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42002d730)
        /Users/dan/code/go-root/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /Users/dan/code/go-root/src/runtime/signal1_unix.go:304 +0x2d1
runtime.goexit()
        /Users/dan/code/go-root/src/runtime/asm_amd64.s:2086 +0x1

goroutine 10 [IO wait]:
net.runtime_pollWait(0xa58fd0, 0x72, 0x7)
        /Users/dan/code/go-root/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42015f5d0, 0x72, 0xc420040c20, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42015f5d0, 0x5ce520, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42015f570, 0xc420173000, 0x1000, 0x1000, 0x0, 0x5ce520, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002e9e8, 0xc420173000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /Users/dan/code/go-root/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc42016cb40)
        /Users/dan/code/go-root/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc42016cb40, 0xc4201b2b0a, 0xc420161a70, 0xc, 0x423e3e, 0x4, 0xc4201b6200)
        /Users/dan/code/go-root/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadBytes(0xc42016cb40, 0xa, 0xc4201b6200, 0x1, 0x1, 0x400000000000000, 0x1)
        /Users/dan/code/go-root/src/bufio/bufio.go:408 +0x66
github.com/DanielOaks/oragono/irc.(*Socket).Read(0xc4201632a0, 0xc42009d380, 0xc4200aa540, 0xc4201b2ba0, 0x0)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/socket.go:82 +0x43
github.com/DanielOaks/oragono/irc.(*Client).run(0xc4200aa540)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:149 +0xe3
created by github.com/DanielOaks/oragono/irc.NewClient
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:129 +0x436

goroutine 14 [IO wait]:                                                                                                                                                                  [43/6661]
net.runtime_pollWait(0xa58e50, 0x72, 0xa)
        /Users/dan/code/go-root/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42015fbf0, 0x72, 0xc42003ac20, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42015fbf0, 0x5ce520, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42015fb90, 0xc4201ab000, 0x1000, 0x1000, 0x0, 0x5ce520, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002e9f8, 0xc4201ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /Users/dan/code/go-root/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc42016cfc0)
        /Users/dan/code/go-root/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc42016cfc0, 0xa, 0x1, 0x5, 0xc4201ba015, 0xc4201ba030, 0xc4201a6508)
        /Users/dan/code/go-root/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadBytes(0xc42016cfc0, 0xa, 0xc4201ba020, 0x1, 0x1, 0xdd00000000000000, 0x3)
        /Users/dan/code/go-root/src/bufio/bufio.go:408 +0x66
github.com/DanielOaks/oragono/irc.(*Socket).Read(0xc4201ac840, 0xc42009d380, 0xc4200aa8c0, 0xc4201be000, 0x0)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/socket.go:82 +0x43
github.com/DanielOaks/oragono/irc.(*Client).run(0xc4200aa8c0)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:149 +0xe3
created by github.com/DanielOaks/oragono/irc.NewClient
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:129 +0x436

goroutine 16 [IO wait]:
net.runtime_pollWait(0xa58d90, 0x72, 0xb)
        /Users/dan/code/go-root/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42015ff00, 0x72, 0xc42003bc20, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42015ff00, 0x5ce520, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42015fea0, 0xc4201b0000, 0x1000, 0x1000, 0x0, 0x5ce520, 0xc4200101d0)
        /Users/dan/code/go-root/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002ea00, 0xc4201b0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /Users/dan/code/go-root/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc42016d200)
        /Users/dan/code/go-root/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc42016d200, 0xa, 0x1, 0x5, 0xc4201b6245, 0xc4201b6260, 0xc4201a6808)
        /Users/dan/code/go-root/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadBytes(0xc42016d200, 0xa, 0xc4201b6250, 0x1, 0x1, 0xdd00000000000000, 0x3)
        /Users/dan/code/go-root/src/bufio/bufio.go:408 +0x66
github.com/DanielOaks/oragono/irc.(*Socket).Read(0xc4201ad300, 0xc42009d380, 0xc4200aaa80, 0xc4201b2c90, 0x0)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/socket.go:82 +0x43
github.com/DanielOaks/oragono/irc.(*Client).run(0xc4200aaa80)
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:149 +0xe3
created by github.com/DanielOaks/oragono/irc.NewClient
        /Users/dan/code/go/src/github.com/DanielOaks/oragono/irc/client.go:129 +0x436
```

**Comment by DanielOaks** [comment]
efb3000717736c014d07b2c06b9ed79489ea39e9 make client_loopup_set use an RWMutex, which works well.

6f7c6832475361febecb0b5354da91af8d6154d1 on `develop` tries to make channel.members do the same, though there are some fairly decent issues with it. Just need to figure out where it's unnecessarily requesting mutexes and fix up those cases.

**Comment by DanielOaks** [comment]
c39bebc696b5a204dde8740f0134bed296d80090 and e9324c32501502a0b00fcfe35ec4a776f44669f5 clean this up further, to the point where I'm relatively happy with it ([irctest](https://github.com/danieloaks/irctest) doesn't throw back any further hangs or errors)
